### ISSUE TITLE
Playback gets stuck on a single note

### ISSUE THREAD

**Issue by ebowden** [kosua20/MIDIVisualizer#36] opened 2019-11-24 05:33 UTC
Trying to visualize a pair of trombones for a cover (midi attached as zip because github doesn't allow mids). The playback appears to get stuck continuously playing the first note for a very long time. This is on the 64-bit windows release 4.1. Thanks for this project!

[Gerudo_Valley-Trombones.zip](https://github.com/kosua20/MIDIVisualizer/files/3883233/Gerudo_Valley-Trombones.zip)

The midi was exported from Musescore 3.2.3.7635 if it makes a difference.

**Comment by kosua20** [comment] 2019-12-15 14:19
Hello, thank you for reporting this issue and providing the midi file! I've managed to reproduce the bug on my local test machine, so I'll be able to investigate this in the near future.

**Comment by ekuiter** [comment] 2020-03-27 16:46
This problem is likely due to tempo changes in the MIDI file. I [fixed it](https://github.com/ekuiter/MIDIVisualizer) by switching over to libmidi. With the [latest release](https://github.com/ekuiter/MIDIVisualizer/releases/tag/v5.0), the file seems to play correctly.

**Comment by kosua20** [comment] 2020-07-24 21:37
Hello, I'm very happy to say that I've finally had a bit of time to allocate to MIDIVisualizer, and the timing issues are now fixed (hopefully for good this time)! The latest v5.1 version has now been [released](https://github.com/kosua20/MIDIVisualizer/releases/tag/v5.1) with these fixes.

**Closed** 2020-07-25 18:08 UTC
Labels: bug
